# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-19 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    replaces = [('system', '0001_initial'), ('system', '0002_pc_location'), ('system', '0003_auto_20180607_1324'), ('system', '0004_auto_20180607_1325'), ('system', '0005_auto_20190225_1620')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=4096)),
                ('owner_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='system.Configuration', verbose_name='owner configuration')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uid', models.CharField(max_length=255, verbose_name='uid')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('value_type', models.CharField(choices=[(b'STRING', 'String'), (b'INT', 'Integer'), (b'DATE', 'Date'), (b'FILE', 'File')], max_length=10, verbose_name='value type')),
                ('position', models.IntegerField(verbose_name='position')),
                ('mandatory', models.BooleanField(default=True, verbose_name='mandatory')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'NEW', 'jobstatus:New'), (b'SUBMITTED', 'jobstatus:Submitted'), (b'RUNNING', 'jobstatus:Running'), (b'FAILED', 'jobstatus:Failed'), (b'DONE', 'jobstatus:Done'), (b'RESOLVED', 'jobstatus:Resolved')], default=b'NEW', max_length=10)),
                ('log_output', models.CharField(blank=True, max_length=128000, verbose_name='log output')),
                ('started', models.DateTimeField(null=True, verbose_name='started')),
                ('finished', models.DateTimeField(null=True, verbose_name='finished')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='system.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='PackageInstallInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_add', models.BooleanField(default=True)),
                ('custom_packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_infos', to='system.CustomPackages')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Package')),
                ('package_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='system.PackageList')),
            ],
        ),
        migrations.CreateModel(
            name='BatchParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.CharField(blank=True, max_length=4096, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to=system.models.upload_file_name)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='system.Batch')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Input')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uid', models.CharField(max_length=255, verbose_name='uid')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_update_required', models.BooleanField(default=False, verbose_name='update required')),
                ('do_send_package_info', models.BooleanField(default=True, verbose_name='send package info')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Configuration')),
                ('custom_packages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.CustomPackages')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Distribution')),
                ('package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.PackageList')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='id')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='description')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Configuration')),
                ('custom_packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.CustomPackages')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(max_length=4096, verbose_name='description')),
                ('executable_code', models.FileField(upload_to=b'script_uploads', verbose_name='executable code')),
                ('is_security_script', models.BooleanField(default=False, verbose_name='security script')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocurred_time', models.DateTimeField(verbose_name='occurred')),
                ('reported_time', models.DateTimeField(verbose_name='reported')),
                ('summary', models.CharField(max_length=4096)),
                ('complete_log', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'NEW', 'eventstatus:New'), (b'ASSIGNED', 'eventstatus:Assigned'), (b'RESOLVED', 'eventstatus:Resolved')], default=b'NEW', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.PC')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uid', models.SlugField(verbose_name='uid')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('level', models.CharField(choices=[(b'Critical', 'securitylevel:Critical'), (b'High', 'securitylevel:High'), (b'Normal', 'securitylevel:Normal')], default=b'High', max_length=10)),
                ('alert_groups', models.ManyToManyField(blank=True, related_name='security_problems', to='system.PCGroup')),
                ('alert_users', models.ManyToManyField(blank=True, related_name='security_problems', to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_problems', to='system.Script')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='uid')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Configuration')),
                ('security_alerts', models.ManyToManyField(blank=True, related_name='alert_sites', to='system.SecurityProblem')),
            ],
        ),
        migrations.AddField(
            model_name='securityproblem',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_problems', to='system.Site'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.SecurityProblem'),
        ),
        migrations.AddField(
            model_name='script',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='system.Site'),
        ),
        migrations.AddField(
            model_name='pcgroup',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='system.Site'),
        ),
        migrations.AddField(
            model_name='pc',
            name='pc_groups',
            field=models.ManyToManyField(blank=True, related_name='pcs', to='system.PCGroup'),
        ),
        migrations.AddField(
            model_name='pc',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='system.Site'),
        ),
        migrations.AddField(
            model_name='packagelist',
            name='packages',
            field=models.ManyToManyField(blank=True, through='system.PackageStatus', to='system.Package'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AddField(
            model_name='job',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='system.PC'),
        ),
        migrations.AddField(
            model_name='input',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='system.Script'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='package_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.PackageList'),
        ),
        migrations.AddField(
            model_name='custompackages',
            name='packages',
            field=models.ManyToManyField(blank=True, through='system.PackageInstallInfo', to='system.Package'),
        ),
        migrations.AddField(
            model_name='batch',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Script'),
        ),
        migrations.AddField(
            model_name='batch',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='system.Site'),
        ),
        migrations.AlterField(
            model_name='securityproblem',
            name='level',
            field=models.CharField(choices=[('Critical', 'securitylevel:Critical'), ('High', 'securitylevel:High'), ('Normal', 'securitylevel:Normal')], default='High', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='securityproblem',
            unique_together=set([('uid', 'site')]),
        ),
        migrations.AlterUniqueTogether(
            name='pcgroup',
            unique_together=set([('uid', 'site')]),
        ),
        migrations.AddField(
            model_name='pc',
            name='location',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pc',
            name='mac',
            field=models.CharField(blank=True, max_length=255, verbose_name='mac'),
        ),
        migrations.AlterField(
            model_name='input',
            name='value_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('DATE', 'Date'), ('FILE', 'File')], max_length=10, verbose_name='value type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('NEW', 'jobstatus:New'), ('SUBMITTED', 'jobstatus:Submitted'), ('RUNNING', 'jobstatus:Running'), ('FAILED', 'jobstatus:Failed'), ('DONE', 'jobstatus:Done'), ('RESOLVED', 'jobstatus:Resolved')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='script',
            name='executable_code',
            field=models.FileField(upload_to='script_uploads', verbose_name='executable code'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='status',
            field=models.CharField(choices=[('NEW', 'eventstatus:New'), ('ASSIGNED', 'eventstatus:Assigned'), ('RESOLVED', 'eventstatus:Resolved')], default='NEW', max_length=10),
        ),
        migrations.CreateModel(
            name='AssociatedScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='system.PCGroup')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='system.Script')),
            ],
        ),
        migrations.CreateModel(
            name='AssociatedScriptParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.CharField(blank=True, max_length=4096, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to=system.models.upload_file_name)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together=set([('position', 'script')]),
        ),
        migrations.AddField(
            model_name='associatedscriptparameter',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Input'),
        ),
        migrations.AddField(
            model_name='associatedscriptparameter',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='system.AssociatedScript'),
        ),
        migrations.AlterUniqueTogether(
            name='associatedscript',
            unique_together=set([('position', 'group')]),
        ),
    ]
