# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-22 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190122_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='system.PCGroup')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='system.Script')),
            ],
        ),
        migrations.CreateModel(
            name='AssociatedScriptParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.CharField(blank=True, max_length=4096, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to=system.models.upload_file_name)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Input')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='system.AssociatedScript')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Parameter',
            new_name='BatchParameter',
        ),
    ]
