# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190122_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedscript',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='system.PCGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='associatedscript',
            unique_together=set([('position', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together=set([('position', 'script')]),
        ),
    ]
